### ISSUE TITLE
DNS record conflict when `certificate_verification_dns_record_enabled=true`

### ISSUE THREAD

**Issue by goruha** [cloudposse-terraform-components/aws-amplify#17]
## Describe the Bug
DNS record conflict when `certificate_verification_dns_record_enabled=true`.
Now amplify creates its own DNS records for Amplify managed https certificates.
So having `certificate_verification_dns_record_enabled` tries to create a duplicated DNS record.

## Expected Behavior
Apply should works without any issues

## Steps to Reproduce
Try to deploy this configuration 

```
components:
  terraform:
    amplify/basic:
      metadata:
        component: amplify
      vars:
        enabled: true
        # https://docs.aws.amazon.com/amplify/latest/userguide/setting-up-GitHub-access.html
        github_personal_access_token_secret_path: "/amplify/github_personal_access_token"
        platform: "WEB"
        dns_delegated_component_name: "dns-delegated"
#         dns_delegated_environment_name: "ue2"

        name: "example"
        description: "example Amplify App"
        repository: "https://github.com/cloudposse-tests/amplify"
        environments:
          main:
            branch_name: "main"
            enable_auto_build: true
            backend_enabled: false
            enable_performance_mode: false
            enable_pull_request_preview: false
            framework: "Next.js - SSR"
            stage: "PRODUCTION"
            environment_variables: {}
        domain_config:
          sub_domain:
            - branch_name: "main"
              prefix: "example-prod"
        certificate_verification_dns_record_enabled: true
```
