### ISSUE TITLE
Using Amplify managed HTTPS Certificate creates DNS verification record and leaves it after termination

### ISSUE THREAD

**Issue by goruha** [cloudposse-terraform-components/aws-amplify#18]
## Describe the Bug
Using an Amplify-managed HTTPS Certificate creates a DNS verification record and leaves it after removing the component.
The DNS record prevents deleting the route53 zone so make troubles correctly teardown infrastracture.

## Expected Behavior
All resources created explicitly or implicitly should be under terraform control

## Steps to Reproduce
1. Deploy 
```
components:
  terraform:
    dns-delegated:
      metadata:
        component: dns-delegated
      vars:
        zone_config:
          - subdomain: test
            zone_name: example.net
        request_acm_certificate: false
```

2. Deploy 
```
components:
  terraform:
    amplify/basic:
      metadata:
        component: amplify
      vars:
        enabled: true
        github_personal_access_token_secret_path: "/amplify/github_personal_access_token"
        platform: "WEB"
        dns_delegated_component_name: "dns-delegated"
        dns_delegated_environment_name: "ue2"

        name: "example"
        description: "example Amplify App"
        repository: "https://github.com/cloudposse-tests/amplify"

        environments:
          main:
            branch_name: "main"
            enable_auto_build: true
            backend_enabled: false
            enable_performance_mode: false
            enable_pull_request_preview: false
            framework: "Next.js - SSR"
            stage: "PRODUCTION"
            environment_variables: {}
        domain_config:
          sub_domain:
            - branch_name: "main"
              prefix: "example-prod"
        subdomains_dns_records_enabled: true
        certificate_verification_dns_record_enabled: false
```
3. Remove `amplify/basic` component
4. Remove `dns-delegated` component
5. See the error that `dns-delegated` zone can not be removed because there are 3 DNS records (expected to be 2)

## Possible solutions
1. Document this side effect
2. Create an HTTPS certificate with Terraform and pass it (arn, etc) as a managed certificate to amplify the app.
